using System;
using System.Collections.Concurrent;
using System.Globalization;
using System.IO;
using System.Text;
using System.Threading;
using RosMessageTypes.BuiltinInterfaces;
using RosMessageTypes.Nav;
using RosMessageTypes.Sensor;
using UnityEngine;

namespace Robocon2026.Simulation
{
    /// <summary>
    /// Records the messages generated by Unity before they enter ROS-TCP-Connector.
    /// The writer is deliberately independent from ROS transport: a CSV row means that the
    /// Unity sensor model produced that sample, not that a subscriber happened to receive it.
    /// </summary>
    internal sealed class UnitySensorCsvRecorder : IDisposable
    {
        private enum RecordKind { Imu, Scan, GroundTruth }

        private struct PendingRecord
        {
            public RecordKind Kind;
            public long Sequence;
            public object Message;
        }

        private readonly BlockingCollection<PendingRecord> queue = new();
        private readonly Thread writerThread;
        private readonly string outputDirectory;
        private readonly string manifestPath;
        private readonly string runId;
        private readonly double fixedDeltaTime;
        private readonly string unityVersion;
        private readonly StreamWriter imuWriter;
        private readonly StreamWriter scanWriter;
        private readonly StreamWriter groundTruthWriter;
        private Exception writerFailure;
        private int disposed;
        private long imuWritten;
        private long scanWritten;
        private long groundTruthWritten;
        private long queued;
        private long maximumQueued;

        public string OutputDirectory => outputDirectory;

        public UnitySensorCsvRecorder(double fixedDeltaTime)
        {
            this.fixedDeltaTime = fixedDeltaTime;
            unityVersion = Application.unityVersion;
            runId = DateTime.UtcNow.ToString("yyyyMMdd_HHmmss_fff", CultureInfo.InvariantCulture)
                + "_" + Guid.NewGuid().ToString("N").Substring(0, 8);
            outputDirectory = Path.Combine(Application.dataPath, "..", "SensorRecordings", runId);
            Directory.CreateDirectory(outputDirectory);
            manifestPath = Path.Combine(outputDirectory, "manifest.json");

            imuWriter = CreateWriter("imu.csv");
            scanWriter = CreateWriter("scan.csv");
            groundTruthWriter = CreateWriter("ground_truth.csv");
            imuWriter.WriteLine("seq,stamp_ns,frame_id,orientation_x,orientation_y,orientation_z,orientation_w,orientation_covariance,angular_velocity_x,angular_velocity_y,angular_velocity_z,angular_velocity_covariance,linear_acceleration_x,linear_acceleration_y,linear_acceleration_z,linear_acceleration_covariance");
            scanWriter.WriteLine("seq,stamp_ns,frame_id,angle_min,angle_max,angle_increment,time_increment,scan_time,range_min,range_max,ranges,intensities");
            groundTruthWriter.WriteLine("seq,stamp_ns,frame_id,child_frame_id,position_x,position_y,position_z,orientation_x,orientation_y,orientation_z,orientation_w,pose_covariance,linear_x,linear_y,linear_z,angular_x,angular_y,angular_z,twist_covariance");
            WriteManifest(false);

            writerThread = new Thread(WriterLoop)
            {
                IsBackground = true,
                Name = "UnitySensorCsvRecorder"
            };
            writerThread.Start();
        }

        public void RecordImu(ImuMsg message, long sequence) =>
            Enqueue(RecordKind.Imu, sequence, message);

        public void RecordScan(LaserScanMsg message, long sequence) =>
            Enqueue(RecordKind.Scan, sequence, message);

        public void RecordGroundTruth(OdometryMsg message, long sequence) =>
            Enqueue(RecordKind.GroundTruth, sequence, message);

        private StreamWriter CreateWriter(string name) => new(
            new FileStream(Path.Combine(outputDirectory, name), FileMode.CreateNew, FileAccess.Write,
                FileShare.Read, 1024 * 1024, FileOptions.SequentialScan),
            new UTF8Encoding(false), 1024 * 1024);

        private void Enqueue(RecordKind kind, long sequence, object message)
        {
            if (Volatile.Read(ref disposed) != 0)
                throw new ObjectDisposedException(nameof(UnitySensorCsvRecorder));
            if (writerFailure != null)
                throw new InvalidOperationException("Sensor CSV writer failed.", writerFailure);

            var pending = new PendingRecord { Kind = kind, Sequence = sequence, Message = message };
            var current = Interlocked.Increment(ref queued);
            try
            {
                queue.Add(pending);
                while (current > Volatile.Read(ref maximumQueued))
                {
                    var observed = Volatile.Read(ref maximumQueued);
                    if (observed >= current || Interlocked.CompareExchange(ref maximumQueued, current, observed) == observed)
                        break;
                }
            }
            catch
            {
                Interlocked.Decrement(ref queued);
                throw;
            }
        }

        private void WriterLoop()
        {
            try
            {
                foreach (var pending in queue.GetConsumingEnumerable())
                {
                    switch (pending.Kind)
                    {
                        case RecordKind.Imu:
                            WriteImu((ImuMsg)pending.Message, pending.Sequence);
                            imuWritten++;
                            break;
                        case RecordKind.Scan:
                            WriteScan((LaserScanMsg)pending.Message, pending.Sequence);
                            scanWritten++;
                            break;
                        case RecordKind.GroundTruth:
                            WriteGroundTruth((OdometryMsg)pending.Message, pending.Sequence);
                            groundTruthWritten++;
                            break;
                    }
                    Interlocked.Decrement(ref queued);
                }
                imuWriter.Flush();
                scanWriter.Flush();
                groundTruthWriter.Flush();
            }
            catch (Exception exception)
            {
                writerFailure = exception;
            }
        }

        private void WriteImu(ImuMsg message, long sequence)
        {
            var writer = imuWriter;
            WritePrefix(writer, sequence, message.header.stamp, message.header.frame_id);
            WriteNumber(writer, message.orientation.x); writer.Write(',');
            WriteNumber(writer, message.orientation.y); writer.Write(',');
            WriteNumber(writer, message.orientation.z); writer.Write(',');
            WriteNumber(writer, message.orientation.w); writer.Write(',');
            WriteArray(writer, message.orientation_covariance); writer.Write(',');
            WriteNumber(writer, message.angular_velocity.x); writer.Write(',');
            WriteNumber(writer, message.angular_velocity.y); writer.Write(',');
            WriteNumber(writer, message.angular_velocity.z); writer.Write(',');
            WriteArray(writer, message.angular_velocity_covariance); writer.Write(',');
            WriteNumber(writer, message.linear_acceleration.x); writer.Write(',');
            WriteNumber(writer, message.linear_acceleration.y); writer.Write(',');
            WriteNumber(writer, message.linear_acceleration.z); writer.Write(',');
            WriteArray(writer, message.linear_acceleration_covariance);
            writer.WriteLine();
        }

        private void WriteScan(LaserScanMsg message, long sequence)
        {
            var writer = scanWriter;
            WritePrefix(writer, sequence, message.header.stamp, message.header.frame_id);
            WriteNumber(writer, message.angle_min); writer.Write(',');
            WriteNumber(writer, message.angle_max); writer.Write(',');
            WriteNumber(writer, message.angle_increment); writer.Write(',');
            WriteNumber(writer, message.time_increment); writer.Write(',');
            WriteNumber(writer, message.scan_time); writer.Write(',');
            WriteNumber(writer, message.range_min); writer.Write(',');
            WriteNumber(writer, message.range_max); writer.Write(',');
            WriteArray(writer, message.ranges); writer.Write(',');
            WriteArray(writer, message.intensities);
            writer.WriteLine();
        }

        private void WriteGroundTruth(OdometryMsg message, long sequence)
        {
            var writer = groundTruthWriter;
            WritePrefix(writer, sequence, message.header.stamp, message.header.frame_id);
            WriteCsvString(writer, message.child_frame_id); writer.Write(',');
            var pose = message.pose.pose;
            WriteNumber(writer, pose.position.x); writer.Write(',');
            WriteNumber(writer, pose.position.y); writer.Write(',');
            WriteNumber(writer, pose.position.z); writer.Write(',');
            WriteNumber(writer, pose.orientation.x); writer.Write(',');
            WriteNumber(writer, pose.orientation.y); writer.Write(',');
            WriteNumber(writer, pose.orientation.z); writer.Write(',');
            WriteNumber(writer, pose.orientation.w); writer.Write(',');
            WriteArray(writer, message.pose.covariance); writer.Write(',');
            var twist = message.twist.twist;
            WriteNumber(writer, twist.linear.x); writer.Write(',');
            WriteNumber(writer, twist.linear.y); writer.Write(',');
            WriteNumber(writer, twist.linear.z); writer.Write(',');
            WriteNumber(writer, twist.angular.x); writer.Write(',');
            WriteNumber(writer, twist.angular.y); writer.Write(',');
            WriteNumber(writer, twist.angular.z); writer.Write(',');
            WriteArray(writer, message.twist.covariance);
            writer.WriteLine();
        }

        private static void WritePrefix(StreamWriter writer, long sequence, TimeMsg stamp, string frameId)
        {
            writer.Write(sequence.ToString(CultureInfo.InvariantCulture));
            writer.Write(',');
            writer.Write(ToNanoseconds(stamp).ToString(CultureInfo.InvariantCulture));
            writer.Write(',');
            WriteCsvString(writer, frameId);
            writer.Write(',');
        }

        private static long ToNanoseconds(TimeMsg stamp) =>
            checked(Convert.ToInt64(stamp.sec, CultureInfo.InvariantCulture) * 1_000_000_000L
                + Convert.ToInt64(stamp.nanosec, CultureInfo.InvariantCulture));

        private static void WriteCsvString(StreamWriter writer, string value)
        {
            writer.Write('"');
            writer.Write((value ?? string.Empty).Replace("\"", "\"\""));
            writer.Write('"');
        }

        private static void WriteArray(StreamWriter writer, double[] values)
        {
            writer.Write('"');
            for (var i = 0; i < values.Length; i++)
            {
                if (i != 0) writer.Write(';');
                WriteNumber(writer, values[i]);
            }
            writer.Write('"');
        }

        private static void WriteArray(StreamWriter writer, float[] values)
        {
            writer.Write('"');
            for (var i = 0; i < values.Length; i++)
            {
                if (i != 0) writer.Write(';');
                WriteNumber(writer, values[i]);
            }
            writer.Write('"');
        }

        private static void WriteNumber(StreamWriter writer, double value)
        {
            if (double.IsPositiveInfinity(value)) writer.Write("inf");
            else if (double.IsNegativeInfinity(value)) writer.Write("-inf");
            else if (double.IsNaN(value)) writer.Write("nan");
            else writer.Write(value.ToString("R", CultureInfo.InvariantCulture));
        }

        private static void WriteNumber(StreamWriter writer, float value)
        {
            if (float.IsPositiveInfinity(value)) writer.Write("inf");
            else if (float.IsNegativeInfinity(value)) writer.Write("-inf");
            else if (float.IsNaN(value)) writer.Write("nan");
            else writer.Write(value.ToString("R", CultureInfo.InvariantCulture));
        }

        private void WriteManifest(bool complete)
        {
            var json = "{\n"
                + "  \"schema_version\": 1,\n"
                + "  \"run_id\": \"" + EscapeJson(runId) + "\",\n"
                + "  \"created_utc\": \"" + DateTime.UtcNow.ToString("O", CultureInfo.InvariantCulture) + "\",\n"
                + "  \"unity_version\": \"" + EscapeJson(unityVersion) + "\",\n"
                + "  \"fixed_delta_time_sec\": " + fixedDeltaTime.ToString("R", CultureInfo.InvariantCulture) + ",\n"
                + "  \"topics\": {\"/imu/data\": \"sensor_msgs/msg/Imu\", \"/scan\": \"sensor_msgs/msg/LaserScan\", \"/ground_truth_pose\": \"nav_msgs/msg/Odometry\"},\n"
                + "  \"complete\": " + (complete ? "true" : "false") + ",\n"
                + "  \"written_counts\": {\"imu\": " + imuWritten + ", \"scan\": " + scanWritten + ", \"ground_truth\": " + groundTruthWritten + "},\n"
                + "  \"maximum_pending_records\": " + maximumQueued + "\n"
                + "}\n";
            File.WriteAllText(manifestPath, json, new UTF8Encoding(false));
        }

        private static string EscapeJson(string value) => (value ?? string.Empty)
            .Replace("\\", "\\\\").Replace("\"", "\\\"");

        public void Dispose()
        {
            if (Interlocked.Exchange(ref disposed, 1) != 0) return;
            queue.CompleteAdding();
            if (!writerThread.Join(TimeSpan.FromSeconds(30)))
                throw new TimeoutException("Timed out while flushing Unity sensor CSV records.");
            imuWriter.Dispose();
            scanWriter.Dispose();
            groundTruthWriter.Dispose();
            queue.Dispose();
            WriteManifest(writerFailure == null);
            if (writerFailure != null)
                throw new InvalidOperationException("Sensor CSV writer failed.", writerFailure);
        }
    }
}
